site_name: Reloaded MkDocs Theme
site_url: https://github.com/Reloaded-Project/Reloaded.MkDocsMaterial.Themes.R2

repo_name: Reloaded-Project/Reloaded.MkDocsMaterial.Themes.R2
repo_url: https://github.com/Reloaded-Project/Reloaded.MkDocsMaterial.Themes.R2
use_directory_urls: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Reloaded-Project
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thesewer56?lang=en-GB

extra_css:
  - Stylesheets/extra.css

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    scheme: reloaded3-slate
  features:
    - navigation.instant

plugins:
  - offline
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - redirects:
      redirect_maps:
        "index.md": "Pages/private/index.md"

nav:
  - Home: Pages/private/index.md
  - License: Pages/license.md
  - Contributing: Pages/contributing.md
  - Migration Guide: Pages/migration-guide.md
  - Testing Zone: Pages/private/testing-zone.md
